module.exports = [
  // Admin-related (English)
  "admin",
  "administrator",
  "root",
  "sysadmin",
  "superuser",
  "owner",
  "moderator",
  "mod",
  "manager",
  "supervisor",
  "support",
  "helpdesk",
  "admins",
  "admin1",
  "admin2",
  "adm1n",
  "adminroot",
  "adminaccount",

  // Admin-related (Spanish)
  "administrador",
  "administra",
  "superusuario",
  "propietario",
  "moderador",
  "mod",
  "gerente",
  "supervisor",
  "soporte",
  "mesaayuda",
  "ayuda",
  "equipoadmin",
  "cuentadmin",

  // Admin-related (French)
  "administrateur",
  "administre",
  "superutilisateur",
  "propriétaire",
  "modérateur",
  "mod",
  "gestionnaire",
  "superviseur",
  "assistance",
  "supporttechnique",
  "aide",
  "adminéquipe",
  "compteadmin",

  // System or app-specific
  "system",
  "guest",
  "user",
  "null",
  "undefined",
  "test",
  "demo",
  "server",
  "backend",
  "frontend",
  "api",
  "config",
  "localhost",
  "console",
  "database",
  "dbadmin",
  "index",
  "main",
  "cron",
  "scheduler",
  "serviceaccount",

  // System terms (Spanish)
  "sistema",
  "invitado",
  "usuario",
  "prueba",
  "demo",
  "servidor",
  "baseDatos",
  "cuentadeservicio",
  "programador",

  // System terms (French)
  "système",
  "invité",
  "utilisateur",
  "test",
  "démo",
  "serveur",
  "basededonnées",
  "compteService",
  "programmeur",

  // Impersonation risks (English)
  "dev",
  "developer",
  "staff",
  "team",
  "official",
  "verified",
  "bot",
  "ai",
  "security",
  "adminteam",
  "moderation",
  "engineer",
  "custodian",
  "itadmin",
  "techsupport",
  "productteam",
  "qa",
  "ops",
  "infra",
  "cio",
  "cto",

  // Impersonation risks (Spanish)
  "desarrollador",
  "equipo",
  "oficial",
  "verificado",
  "robot",
  "inteligenciaartificial",
  "seguridad",
  "equipoadmin",
  "moderación",
  "ingeniero",
  "soportetecnico",
  "equipoProducto",
  "calidad",
  "operaciones",
  "infraestructura",
  "cto",
  "cio",

  // Impersonation risks (French)
  "développeur",
  "équipe",
  "officiel",
  "vérifié",
  "robot",
  "ia",
  "sécurité",
  "équipeadmin",
  "modération",
  "ingénieur",
  "supporttechnique",
  "équipeProduit",
  "qualité",
  "opérations",
  "infrastructure",
  "directeurtechnique",
  "directeurinfo",

  // Social engineering bait (English)
  "contact",
  "info",
  "supportteam",
  "billing",
  "sales",
  "noreply",
  "mail",
  "email",
  "webmaster",
  "accounts",
  "customer",
  "hr",
  "legal",
  "payments",
  "adminsupport",
  "clientsupport",
  "inquiries",
  "supportdesk",
  "service",
  "subscribe",
  "unsubscribe",
  "notifications",

  // Social engineering bait (Spanish)
  "contacto",
  "informacion",
  "facturacion",
  "ventas",
  "noreply",
  "correo",
  "email",
  "webmaster",
  "cuentas",
  "cliente",
  "rrhh",
  "legal",
  "pagos",
  "ayudaadmin",
  "ayudaclientes",
  "consultas",
  "soportedesk",
  "servicio",
  "suscribirse",
  "cancelarsuscripcion",
  "notificaciones",

  // Social engineering bait (French)
  "contact",
  "infos",
  "facturation",
  "ventes",
  "noreply",
  "courriel",
  "email",
  "webmestre",
  "comptes",
  "client",
  "rh",
  "juridique",
  "paiements",
  "soutienadmin",
  "soutienclient",
  "demandes",
  "bureausupport",
  "service",
  "abonner",
  "désabonner",
  "notifications"
];
